version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "TrackerApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-e1fsfuhr26qy"
s3_prefix = "TrackerApp"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"v1\" FunctionAlias=\"live\""
